apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auto-center

resources:
  # 1. Namespace (deve ser aplicado primeiro)
  - namespace.yaml
  # 2. Configurações
  - configmap.yaml
  - secret.yaml
  # 3. Banco de dados
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  # 4. Aplicação
  - app-deployment.yaml
  - app-service.yaml
  # 5. Autoscaling
  - hpa.yaml

commonLabels:
  managed-by: kustomize
  project: auto-center-fiap

