apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: auto-center
  labels:
    app: mysql
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Remova ou altere storageClassName conforme seu cluster
  # storageClassName: standard

